### ISSUE TITLE
New issuse 

### ISSUE THREAD

**Issue by Xexman** [spooknik/SkyrimSE-Linux-Modding#2]
As i stated before i booted my system to a  previous state before the root install of install_proton(and the first time was not does a root omg).  anyway...  the last up date got the game to launch, but there are still a ton of errors and getskseversion  returns bash: getskseversion: command not found  for full terminal see  below:

ERROR: ld.so: object '/home/manjaro3/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 11651 != 11649, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/manjaro3/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
[manjaro3@manjaro-pc Skyrim Special Edition]$ `~/".steam/root/compatibilitytools.d/skyrim-proton/proton" run skse64_loader.exe`
ERROR: ld.so: object '/home/manjaro3/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/manjaro3/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/manjaro3/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/manjaro3/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/manjaro3/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/manjaro3/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/manjaro3/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/manjaro3/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/manjaro3/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/manjaro3/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/manjaro3/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/manjaro3/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/manjaro3/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Setting breakpad minidump AppID = 489830
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198062797824 [API loaded no]
Unable to read VR Path Registry from C:\users\steamuser\Local Settings\Application Data\openvr\openvrpaths.vrpath
Fossilize INFO: Overriding serialization path: "/home/manjaro3/.local/share/Steam/steamapps/shadercache/489830/steamapprun_pipeline_cache".
AL lib: (WW) GetSymbol: Failed to load jack_error_callback: /home/manjaro3/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64/libjack.so.0: undefined symbol: jack_error_callback
AL lib: (WW) jack_msg_handler: Cannot connect to server socket err = No such file or directory
AL lib: (WW) jack_msg_handler: Cannot connect to server socket
AL lib: (WW) jack_msg_handler: jack server is not running or cannot be started
AL lib: (WW) ALCjackBackendFactory_init: jack_client_open() failed, 0x11
AL lib: (WW) alc_initconfig: Failed to initialize backend "jack"
Unable to read VR Path Registry from C:\users\steamuser\Local Settings\Application Data\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\users\steamuser\Local Settings\Application Data\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\users\steamuser\Local Settings\Application Data\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\users\steamuser\Local Settings\Application Data\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\users\steamuser\Local Settings\Application Data\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\users\steamuser\Local Settings\Application Data\openvr\openvrpaths.vrpath
ERROR: ld.so: object '/home/manjaro3/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
`getskseversion`
AL lib: (WW) ReleaseContext: 0x7f8ecc041d00 released while current on thread
AL lib: (EE) ReleaseThreadCtx: Context 0x7f8ecc041d00 current for thread being destroyed, possible leak!
bash: SKSE64: command not found
pid 11898 != 11649, skipping destruction (fork without exec?)
[manjaro3@manjaro-pc Skyrim Special Edition]$ `getskseversion`
bash: getskseversion: command not found
pid 11899 != 11649, skipping destruction (fork without exec?)
[manjaro3@manjaro-pc Skyrim Special Edition]$ pid 11667 != 11666, skipping destruction (fork without exec?)
[manjaro3@manjaro-pc Skyrim Special Edition]$

**Comment by spooknik** [comment]
You need to run `getskseversion` from the console in the game not from the terminal. You can access the console by hitting the [tilde key ](https://qph.fs.quoracdn.net/main-qimg-30ce155be6652b3f38a3a792af6dfbca-c)

**Comment by Xexman** [comment]
Oh ok, that returned a version number.
