### ISSUE TITLE
Sound distortion and fixes

### ISSUE THREAD

**Issue by ecbfry** [spooknik/SkyrimSE-Linux-Modding#4]
Thanks for the fantastic guide. With your help, I’ve managed to sort the sound issues I’d been having, and I’m pretty sure it’s now working as it should.

I did still experience some crackling and sound stuttering with proton 3.16 / faudio 19.02, triggered by “busy” areas. This seems to be solved by using the latest custom proton build at https://github.com/kakra/wine-proton (installed over 3.16 beta).

The readme there mentions some additional steps to do with memory allocation, which I haven’t needed.

I’ve also experimented with https://github.com/GloriousEggroll/proton-ge-custom which has the skse patch already applied, but the latest builds gave me problems with directional audio (can only hear sounds I am facing) and weird reverb/echo in interiors.

**Comment by spooknik** [comment]
Thanks for reporting your findings, I want to look into other versions of Proton to see if there's a better solution. Ideally something with the audio fixes applied. Audio is really touchy in Skyrim and I tried and failed so many times to get something that works on my system. 

If you feel like it, feel free to fork my repo and change anything you think needs it.
